In [1]:
pip install pycoingecko

Requirement already satisfied: pycoingecko in /Users/amiraali/opt/anaconda3/lib/python3.9/site-packages (2.2.0)
Requirement already satisfied: requests in /Users/amiraali/opt/anaconda3/lib/python3.9/site-packages (from pycoingecko) (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/amiraali/opt/anaconda3/lib/python3.9/site-packages (from requests->pycoingecko) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/amiraali/opt/anaconda3/lib/python3.9/site-packages (from requests->pycoingecko) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in /Users/amiraali/opt/anaconda3/lib/python3.9/site-packages (from requests->pycoingecko) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/amiraali/opt/anaconda3/lib/python3.9/site-packages (from requests->pycoingecko) (2021.10.8)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from pycoingecko import CoinGeckoAPI
cg = CoinGeckoAPI()

In [3]:
data=cg.get_exchanges_list()
data

[{'id': 'binance',
  'name': 'Binance',
  'year_established': 2017,
  'country': 'Cayman Islands',
  'description': '',
  'url': 'https://www.binance.com/',
  'image': 'https://assets.coingecko.com/markets/images/52/small/binance.jpg?1519353250',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 1,
  'trade_volume_24h_btc': 319257.20564049354,
  'trade_volume_24h_btc_normalized': 319257.20564049354},
 {'id': 'okex',
  'name': 'OKX',
  'year_established': 2013,
  'country': 'Belize',
  'description': '',
  'url': 'https://www.okx.com',
  'image': 'https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1642428377',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 2,
  'trade_volume_24h_btc': 85569.98612513798,
  'trade_volume_24h_btc_normalized': 85569.98612513798},
 {'id': 'crypto_com',
  'name': 'Crypto.com Exchange',
  'year_established': 2019,
  'country': 'Cayman Islands',
  'description': 'Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards',
  'url': 'https://crypto.com/exchange',
  'image': 'https://assets.coingecko.com/markets/images/589/small/Crypto.jpg?1629861084',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 3,
  'trade_volume_24h_btc': 67495.30052510073,
  'trade_volume_24h_btc_normalized': 67495.30052510073},
 {'id': 'gdax',
  'name': 'Coinbase Exchange',
  'year_established': 2012,
  'country': 'United States',
  'description': '',
  'url': 'https://www.coinbase.com',
  'image': 'https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1621471875',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 4,
  'trade_volume_24h_btc': 52034.135451875525,
  'trade_volume_24h_btc_normalized': 52034.135451875525},
 {'id': 'huobi',
  'name': 'Huobi Global',
  'year_established': 2013,
  'country': 'Seychelles',
  'description': '',
  'url': 'https://www.huobi.com',
  'image': 'https://assets.coingecko.com/markets/images/25/small/1481589873352_.pic_hd.jpg?1589962155',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 5,
  'trade_volume_24h_btc': 53054.08313358769,
  'trade_volume_24h_btc_normalized': 53054.08313358769},
 {'id': 'gate',
  'name': 'Gate.io',
  'year_established': None,
  'country': 'Hong Kong',
  'description': 'Gate was established in 2013, and it is the top 10 exchanges in the world in terms of authentic trading volume. It is also the first choice of over 8 million registered customers, covering 130+ countries worldwide, as we are providing the most comprehensive digital asset solutions.',
  'url': 'https://gate.io/',
  'image': 'https://assets.coingecko.com/markets/images/60/small/gateio.jpg?1519793974',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 6,
  'trade_volume_24h_btc': 47788.326562385526,
  'trade_volume_24h_btc_normalized': 47788.326562385526},
 {'id': 'kucoin',
  'name': 'KuCoin',
  'year_established': 2014,
  'country': 'Seychelles',
  'description': '',
  'url': 'https://www.kucoin.com/',
  'image': 'https://assets.coingecko.com/markets/images/61/small/kucoin.png?1640584259',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 7,
  'trade_volume_24h_btc': 46434.71715709252,
  'trade_volume_24h_btc_normalized': 46434.71715709252},
 {'id': 'mxc',
  'name': 'MEXC Global',
  'year_established': 2018,
  'country': None,
  'description': 'Established in April 2018, MEXC Global is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.',
  'url': 'https://www.mexc.com/',
  'image': 'https://assets.coingecko.com/markets/images/409/small/WeChat_Image_20210622160936.png?1624349423',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 8,
  'trade_volume_24h_btc': 40149.25091102137,
  'trade_volume_24h_btc_normalized': 40149.25091102137},
 {'id': 'ftx_spot',
  'name': 'FTX',
  'year_established': 2019,
  'country': 'Antigua and Barbuda',
  'description': '',
  'url': 'https://ftx.com/',
  'image': 'https://assets.coingecko.com/markets/images/451/small/F.png?1609051590',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 9,
  'trade_volume_24h_btc': 36911.29196620253,
  'trade_volume_24h_btc_normalized': 36911.29196620253},
 {'id': 'kraken',
  'name': 'Kraken',
  'year_established': 2011,
  'country': 'United States',
  'description': '',
  'url': 'https://r.kraken.com/c/2223866/687155/10583',
  'image': 'https://assets.coingecko.com/markets/images/29/small/kraken.jpg?1584251255',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 10,
  'trade_volume_24h_btc': 17709.175892240968,
  'trade_volume_24h_btc_normalized': 17709.175892240968},
 {'id': 'wootrade',
  'name': 'WOO Network',
  'year_established': 2019,
  'country': None,
  'description': 'WOO Network is a deep liquidity network connecting traders, exchanges, institutions, and DeFi platforms with democratized access to the best-in-class liquidity and trading execution at lower or zero cost. Its flagship, WOO X, is a professional trading platform featuring customizable modules and lower to zero fees complete with deep liquidity. WOO Network was founded by Kronos Research, a quantitative trading firm generating $5-10B in daily volume.',
  'url': 'https://woo.org/',
  'image': 'https://assets.coingecko.com/markets/images/683/small/wootrade.jpg?1624621149',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 11,
  'trade_volume_24h_btc': 17217.348276413493,
  'trade_volume_24h_btc_normalized': 13743.273303116246},
 {'id': 'bitfinex',
  'name': 'Bitfinex',
  'year_established': 2014,
  'country': 'British Virgin Islands',
  'description': '',
  'url': 'https://www.bitfinex.com',
  'image': 'https://assets.coingecko.com/markets/images/4/small/BItfinex.png?1615895883',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 12,
  'trade_volume_24h_btc': 13482.238328885573,
  'trade_volume_24h_btc_normalized': 13482.238328885573},
 {'id': 'bybit_spot',
  'name': 'Bybit (Spot)',
  'year_established': 2018,
  'country': None,
  'description': '',
  'url': 'https://www.bybit.com',
  'image': 'https://assets.coingecko.com/markets/images/698/small/bybit_spot.png?1629971794',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 13,
  'trade_volume_24h_btc': 8418.215722278239,
  'trade_volume_24h_btc_normalized': 8418.215722278239},
 {'id': 'binance_us',
  'name': 'Binance US',
  'year_established': 2019,
  'country': 'United States',
  'description': '',
  'url': 'https://www.binance.us/en',
  'image': 'https://assets.coingecko.com/markets/images/469/small/Binance.png?1568875842',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 14,
  'trade_volume_24h_btc': 6590.062641835026,
  'trade_volume_24h_btc_normalized': 6590.062641835026},
 {'id': 'gemini',
  'name': 'Gemini',
  'year_established': 2014,
  'country': 'United States',
  'description': '',
  'url': 'https://gemini.sjv.io/bZ49k',
  'image': 'https://assets.coingecko.com/markets/images/50/small/gemini.png?1605704107',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 15,
  'trade_volume_24h_btc': 2724.0895273713963,
  'trade_volume_24h_btc_normalized': 2724.0895273713963},
 {'id': 'bittrex',
  'name': 'Bittrex',
  'year_established': 2014,
  'country': 'United States',
  'description': '',
  'url': 'https://bittrex.com/',
  'image': 'https://assets.coingecko.com/markets/images/10/small/BG-color-250x250_icon.png?1596167574',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 16,
  'trade_volume_24h_btc': 1254.5624586439872,
  'trade_volume_24h_btc_normalized': 1254.5624586439872},
 {'id': 'bitso',
  'name': 'Bitso',
  'year_established': 2014,
  'country': 'Mexico',
  'description': '',
  'url': 'https://bitso.com',
  'image': 'https://assets.coingecko.com/markets/images/8/small/Bitso-icon-dark.png?1581909156',
  'has_trading_incentive': False,
  'trust_score': 10,
  'trust_score_rank': 17,
  'trade_volume_24h_btc': 944.7531384216438,
  'trade_volume_24h_btc_normalized': 944.7531384216438},
 {'id': 'digifinex',
  'name': 'Digifinex',
  'year_established': 2018,
  'country': 'Seychelles',
  'description': '',
  'url': 'https://www.digifinex.com/',
  'image': 'https://assets.coingecko.com/markets/images/225/small/DF_logo.png?1594264355',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 18,
  'trade_volume_24h_btc': 53539.291098371395,
  'trade_volume_24h_btc_normalized': 53539.291098371395},
 {'id': 'bitmart',
  'name': 'BitMart',
  'year_established': 2017,
  'country': 'Cayman Islands',
  'description': '',
  'url': 'https://www.bitmart.com/en',
  'image': 'https://assets.coingecko.com/markets/images/239/small/Bitmart.png?1628066397',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 19,
  'trade_volume_24h_btc': 43784.19910618085,
  'trade_volume_24h_btc_normalized': 43784.19910618085},
 {'id': 'lbank',
  'name': 'LBank',
  'year_established': 2017,
  'country': 'British Virgin Islands',
  'description': 'LBank Exchange, founded in 2015, is a global trading platform for various crypto assets. LBank Exchange provides its users with crypto trading, specialized financial derivatives, and professional asset management services. It has become one of the most popular and trusted crypto trading platforms with over 6.4 million users from now more than 210 regions around the world.',
  'url': 'https://www.lbank.info/',
  'image': 'https://assets.coingecko.com/markets/images/118/small/LBank%E5%9C%86%E6%A0%87.png?1572923264',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 20,
  'trade_volume_24h_btc': 30553.625128136155,
  'trade_volume_24h_btc_normalized': 30553.625128136155},
 {'id': 'bkex',
  'name': 'BKEX',
  'year_established': 2018,
  'country': 'British Virgin Islands',
  'description': '',
  'url': 'https://www.bkex.com/',
  'image': 'https://assets.coingecko.com/markets/images/293/small/New_BKEX_logo.png?1646724631',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 21,
  'trade_volume_24h_btc': 26521.83038684638,
  'trade_volume_24h_btc_normalized': 26521.83038684638},
 {'id': 'phemex',
  'name': 'Phemex',
  'year_established': 2019,
  'country': 'Singapore',
  'description': 'Launched in 2019, Phemex is a Singapore-based cryptocurrency and derivatives trading platform led by former Morgan Stanley executives. Serving around 2 million active users in over 200 countries, Phemex supports 37+ trading pairs with up to 100x leverage. It was also the first major exchange to pioneer an optional premium membership model for zero spot trading fees.\r\n\r\n-  Fee Structure: 0.025% maker fee and 0.075% taker fee\r\n-  Up to $100 Welcome Bonus for new users\r\n-  Earn up to 8.5% APY interest income on crypto assets\r\n-  Free academy with 450+ carefully curated articles about crypto & trading\r\n-  Security: Hierarchical Deterministic Cold Wallet System with 2-level human scrutiny offline signatures.',
  'url': 'https://phemex.com/',
  'image': 'https://assets.coingecko.com/markets/images/564/small/Phemex_logo_4.png?1641357471',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 22,
  'trade_volume_24h_btc': 7028.036760242018,
  'trade_volume_24h_btc_normalized': 7028.036760242018},
 {'id': 'btse',
  'name': 'BTSE',
  'year_established': 2018,
  'country': 'British Virgin Islands',
  'description': 'BTSE is your Bitcoin futures exchange to trade with confidence and ease.\r\n\r\nBTSE‘s mission is to make institutional-grade security and stability available to every crypto trader.\r\n\r\nBTSE’s platform is built to facilitate reliable 24/7 trading. It uses an extremely powerful matching engine that eliminates the risk of system overloads, as well as horizontal scaling which enables BTSE to do hot upgrades with zero downtime. BTSE’s insurance fund, strict security protocols, and self-hosted servers allow for the highest level of security for our traders.',
  'url': 'https://www.btse.com/',
  'image': 'https://assets.coingecko.com/markets/images/464/small/BTSE.jpg?1568012415',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 23,
  'trade_volume_24h_btc': 5541.693804559315,
  'trade_volume_24h_btc_normalized': 5541.693804559315},
 {'id': 'bitstamp',
  'name': 'Bitstamp',
  'year_established': 2013,
  'country': 'United Kingdom',
  'description': None,
  'url': 'https://www.bitstamp.net/',
  'image': 'https://assets.coingecko.com/markets/images/9/small/bitstamp.jpg?1519627979',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 24,
  'trade_volume_24h_btc': 5517.869979649284,
  'trade_volume_24h_btc_normalized': 5517.869979649284},
 {'id': 'btcturk',
  'name': 'BtcTurk PRO',
  'year_established': 2013,
  'country': 'Turkey',
  'description': '',
  'url': 'https://pro.btcturk.com/',
  'image': 'https://assets.coingecko.com/markets/images/223/small/BTCTurk-exchange.jpg?1536726120',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 25,
  'trade_volume_24h_btc': 4423.01175918689,
  'trade_volume_24h_btc_normalized': 4423.01175918689},
 {'id': 'dextrade',
  'name': 'Dex-Trade',
  'year_established': 2019,
  'country': 'Belize',
  'description': 'Dex-Trade is a centralized cryptocurrency exchange founded in 2017 and registered in Belize. This is a modern space for safe and comfortable trading with minimal commissions.\r\n\r\nDex-Trade is a universal exchange for both beginners and professional traders. The minimum spread and high liquidity in order books allow you to trade efficiently with orders of any volume.\r\nAlong with global opportunities, the exchange also provides a demo trading mode for risk-free testing of your trading strategies. Our dedicated support team is online 24/7 to assist you with any questions.\r\n\r\nYou can learn more about Dex-Trade on the website.\r\nhttps://dex-trade.com/info/about\r\n\r\nIf you are looking for listing and promotion options with Dex-Trade please visit our listing page and a personal manager will help you to utilize our proven tools and intelligent market-making system to engage with the vast exchange community in the best possible way. https://dex-trade.com/listing',
  'url': 'https://dex-trade.com/',
  'image': 'https://assets.coingecko.com/markets/images/380/small/Dex-Trade_logo_new.png?1599629803',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 26,
  'trade_volume_24h_btc': 4387.064504266461,
  'trade_volume_24h_btc_normalized': 4387.064504266461},
 {'id': 'bitget',
  'name': 'Bitget',
  'year_established': 2018,
  'country': 'Singapore',
  'description': '',
  'url': 'https://www.bitget.com/',
  'image': 'https://assets.coingecko.com/markets/images/540/small/Bitget_new_logo_2.png?1630049618',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 27,
  'trade_volume_24h_btc': 3611.242553482346,
  'trade_volume_24h_btc_normalized': 3611.242553482346},
 {'id': 'bitkub',
  'name': 'Bitkub',
  'year_established': 2018,
  'country': 'Thailand',
  'description': '',
  'url': 'https://www.bitkub.com',
  'image': 'https://assets.coingecko.com/markets/images/249/small/bitkub.png?1537180687',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 28,
  'trade_volume_24h_btc': 1890.7187230579586,
  'trade_volume_24h_btc_normalized': 1890.7187230579586},
 {'id': 'exmo',
  'name': 'EXMO',
  'year_established': 2013,
  'country': 'United Kingdom',
  'description': '',
  'url': 'https://exmo.com/',
  'image': 'https://assets.coingecko.com/markets/images/59/small/new_logo-1.jpg?1634814504',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 29,
  'trade_volume_24h_btc': 1523.591570543045,
  'trade_volume_24h_btc_normalized': 1523.591570543045},
 {'id': 'tokenize',
  'name': 'Tokenize',
  'year_established': 2018,
  'country': 'Singapore',
  'description': '',
  'url': 'https://tokenize.exchange/',
  'image': 'https://assets.coingecko.com/markets/images/383/small/tokenize-exchange.png?1586138532',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 30,
  'trade_volume_24h_btc': 1115.1360528299997,
  'trade_volume_24h_btc_normalized': 1115.1360528299997},
 {'id': 'blockchain_com',
  'name': 'Blockchain.com',
  'year_established': 2012,
  'country': 'United Kingdom',
  'description': '',
  'url': 'https://www.blockchain.com/',
  'image': 'https://assets.coingecko.com/markets/images/613/small/unnamedddd.png?1610503741',
  'has_trading_incentive': False,
  'trust_score': 9,
  'trust_score_rank': 31,
  'trade_volume_24h_btc': 658.7273792124129,
  'trade_volume_24h_btc_normalized': 658.7273792124129},
 {'id': 'upbit',
  'name': 'Upbit',
  'year_established': 2017,
  'country': 'South Korea',
  'description': None,
  'url': 'https://upbit.com',
  'image': 'https://assets.coingecko.com/markets/images/117/small/upbit.png?1520388800',
  'has_trading_incentive': False,
  'trust_score': 8,
  'trust_score_rank': 33,
  'trade_volume_24h_btc': 69755.65580241718,
  'trade_volume_24h_btc_normalized': 69755.65580241718},
 {'id': 'aax',
  'name': 'AAX',
  'year_established': 2019,
  'country': 'Seychelles',
  'description': 'AAX is the world’s first cryptocurrency exchange to be powered by LSEG Technology’s Millennium Exchange, the same matching engine at the heart of tier-one capital markets. AAX is a member of London Stock Exchange Group’s global ‘Partner Platform’. Offering OTC, Spot, and Futures trading, quoting more than 50 cryptocurrency pairs and listing 5 perpetual futures contracts for Bitcoin, Ether, Litecoin, Ripple, and EOS, which can be traded with high leverage, AAX provides a secure, deeply liquid, ultra-low latency and fully compliant trading platform. It offers an institutional-grade platform, for everyone. ',
  'url': 'https://www.aax.com',
  'image': 'https://assets.coingecko.com/markets/images/527/small/aax_app_logo.png?1586779427',
  'has_trading_incentive': False,
  'trust_score': 8,
  'trust_score_rank': 34,
  'trade_volume_24h_btc': 63880.497517318225,
  'trade_volume_24h_btc_normalized': 63880.497517318225},
 {'id': 'bitrue',
  'name': 'Bitrue',
  'year_established': 2018,
  'country': 'Singapore',
  'description': '',
  'url': 'https://www.bitrue.com/',
  'image': 'https://assets.coingecko.com/markets/images/254/small/Bitrue_Exchange.png?1637142776',
  'has_trading_incentive': False,
  'trust_score': 8,
  'trust_score_rank': 35,
  'trade_volume_24h_btc': 56267.43938480004,
  'trade_volume_24h_btc_normalized': 56267.43938480004},
 {'id': 'xt',
  'name': 'XT.COM',
  'year_established': 2018,
  'country': 'Seychelles',
  'description': 'Established in Seychelles 2018, and headquartered in Singapore, XT.COM has operation centres in Tokyo, Singapore, Seoul in an effort to globalise our operations. \r\nThe platform has a top-level domain www.xt.com, and currently has more than 3 million registered users, over 300,000 monthly active users, and over 30 million users in the ecosystem.\r\nXT.COM is a comprehensive trading platform that supports 100+ high-quality currencies and 300 trading pairs. It has a rich variety of transactions such as currency transactions, leveraged transactions, OTC transactions, contract transactions, and credit card purchases. We provide users with the safest, most efficient and professional digital asset investment services.',
  'url': 'https://www.xt.com/',

In [4]:
#trust score rank

import pandas as pd
df =pd.DataFrame(data, columns=['name', 'trust_score','trust_score_rank'])
df.set_index('name',inplace=True)
df.head(10)

                     trust_score  trust_score_rank
name
Binance                       10                 1
OKX                           10                 2
Crypto.com Exchange           10                 3
Coinbase Exchange             10                 4
Huobi Global                  10                 5
Gate.io                       10                 6
KuCoin                        10                 7
MEXC Global                   10                 8
FTX                           10                 9
Kraken                        10                10

In [5]:
def get_data(cryptocurrency):
    cryptocurrency_data = cg.get_coin_by_id(cryptocurrency, market_data='true', sparkline='true')
    df = pd.DataFrame.from_dict(cryptocurrency_data, orient='index')
    df.to_csv(r'cryptocurrency_data.csv')
    return df

In [6]:
get_data('bitcoin')

                                                                                 0
id                                                                         bitcoin
symbol                                                                         btc
name                                                                       Bitcoin
asset_platform_id                                                             None
platforms                                                                 {'': ''}
block_time_in_minutes                                                           10
hashing_algorithm                                                          SHA-256
categories                                                        [Cryptocurrency]
public_notice                                                                 None
additional_notices                                                              []
localization                     {'en': 'Bitcoin', 'de': 'Bitcoin', 'es': 'Bitc...
description                      {'en': 'Bitcoin is the first successful intern...
links                            {'homepage': ['http://www.bitcoin.org', '', ''...
image                            {'thumb': 'https://assets.coingecko.com/coins/...
country_origin
genesis_date                                                            2009-01-03
sentiment_votes_up_percentage                                                75.32
sentiment_votes_down_percentage                                              24.68
market_cap_rank                                                                  1
coingecko_rank                                                                   1
coingecko_score                                                             81.034
developer_score                                                             98.939
community_score                                                             73.958
liquidity_score                                                            100.141
public_interest_score                                                          0.0
market_data                      {'current_price': {'aed': 151494, 'ars': 46591...
community_data                   {'facebook_likes': None, 'twitter_followers': ...
developer_data                   {'forks': 32109, 'stars': 63260, 'subscribers'...
public_interest_stats                   {'alexa_rank': 9440, 'bing_matches': None}
status_updates                                                                  []
last_updated                                              2022-04-14T01:07:52.473Z
tickers                          [{'base': 'ETH', 'target': 'BTC', 'market': {'...

In [7]:
def get_historical_data(cryptocurrency, fiat_currency, number_of_days):
    historic_price = cg.get_coin_market_chart_by_id(cryptocurrency, fiat_currency, number_of_days)
    prices = [price[1] for price in historic_price['prices']]
    return prices

In [8]:
import pandas as pd

In [12]:
ethereum = get_historical_data('ethereum', 'USD', 30)

In [13]:
historic_pricesolana = pd.DataFrame(get_historical_data("solana", "USD", 365))
historic_pricesolana

              0
0     27.569507
1     26.451516
2     27.829492
3     25.280265
4     25.010979
..          ...
361  113.006456
362  112.174160
363   99.452525
364  103.503035
365  100.717204

[366 rows x 1 columns]

In [14]:
historic_pricesol = cg.get_coin_market_chart_by_id("solana", "usd", 730)
solaprice=pd.DataFrame(historic_pricesol['prices'], columns=['Time','Solana Price'])
solaprice

              Time  Solana Price
0    1586908800000      0.666673
1    1586995200000      0.637621
2    1587081600000      0.692333
3    1587168000000      0.657449
4    1587254400000      0.676972
..             ...           ...
726  1649635200000    112.174160
727  1649721600000     99.452525
728  1649808000000    103.503035
729  1649894400000    104.844477
730  1649898551000    105.228439

[731 rows x 2 columns]

In [12]:
solaprice.to_csv("solona.csv")

In [11]:
marketcapsol = cg.get_coin_market_chart_by_id("solana", "usd", 730)

In [14]:
solMC=pd.DataFrame(marketcapsol['market_caps'], columns=['Time','Solana Market Cap'])
solMC

              Time  Solana Market Cap
0    1586822400000       6.302364e+06
1    1586908800000       5.306221e+06
2    1586995200000       5.114654e+06
3    1587081600000       5.505929e+06
4    1587168000000       5.348324e+06
..             ...                ...
726  1649548800000       3.700753e+10
727  1649635200000       3.688414e+10
728  1649721600000       3.273150e+10
729  1649808000000       3.394112e+10
730  1649886234000       3.443772e+10

[731 rows x 2 columns]

In [25]:
solMC.to_csv("solonaMC.csv")

In [27]:
volsol = cg.get_coin_market_chart_by_id("solana", "usd", 730)
volsolana=pd.DataFrame(volsol['total_volumes'], columns=['Time','Solana Volume'])
volsolana

              Time  Solana Volume
0    1586563200000   9.267267e+07
1    1586649600000   4.945869e+07
2    1586736000000   3.782101e+07
3    1586822400000   1.957921e+07
4    1586908800000   1.752353e+07
..             ...            ...
725  1649203200000   2.136267e+09
726  1649289600000   3.198016e+09
727  1649376000000   2.381088e+09
728  1649462400000   2.314899e+09
729  1649519026000   1.670543e+09

[730 rows x 2 columns]

In [28]:
volsolana.to_csv("solonaVol.csv")

In [32]:
historic_pricetron = cg.get_coin_market_chart_by_id("tron", "usd", 730)
tronprice=pd.DataFrame(historic_pricetron['prices'], columns=['Time','Tron Price'])
tronprice

              Time  Tron Price
0    1586476800000    0.013435
1    1586563200000    0.012504
2    1586649600000    0.012500
3    1586736000000    0.012708
4    1586822400000    0.012576
..             ...         ...
726  1649203200000    0.069441
727  1649289600000    0.063205
728  1649376000000    0.064453
729  1649462400000    0.062606
730  1649519815000    0.062542

[731 rows x 2 columns]

In [33]:
tronprice.to_csv("tron.csv")

In [34]:
marketcaptron = cg.get_coin_market_chart_by_id("tron", "usd", 730)
tronMC=pd.DataFrame(marketcaptron['market_caps'], columns=['Time','Tron Market Cap'])
tronMC

              Time  Tron Market Cap
0    1586476800000     8.898568e+08
1    1586563200000     8.220813e+08
2    1586649600000     8.257288e+08
3    1586736000000     8.488375e+08
4    1586822400000     8.377505e+08
..             ...              ...
726  1649203200000     7.069255e+09
727  1649289600000     6.436734e+09
728  1649376000000     6.562939e+09
729  1649462400000     6.342604e+09
730  1649519815000     6.360527e+09

[731 rows x 2 columns]

In [35]:
tronMC.to_csv("tronMC.csv")

In [47]:
volumetron = cg.get_coin_market_chart_by_id("tron", "usd", 730)
voltron=pd.DataFrame(volumetron['total_volumes'], columns=['Time','Tron Volume'])
voltron

              Time   Tron Volume
0    1586476800000  1.069727e+09
1    1586563200000  1.179810e+09
2    1586649600000  1.101730e+09
3    1586736000000  1.092810e+09
4    1586822400000  1.297979e+09
..             ...           ...
726  1649203200000  1.400060e+09
727  1649289600000  1.448266e+09
728  1649376000000  9.209929e+08
729  1649462400000  8.567597e+08
730  1649521825000  9.913204e+08

[731 rows x 2 columns]

In [48]:
voltron.to_csv("tronVol.csv")

In [38]:
historic_pricecron = cg.get_coin_market_chart_by_id("crypto-com-chain", "usd", 730)
cronprice=pd.DataFrame(historic_pricecron['prices'], columns=['Time','Cronos Price'])
cronprice

              Time  Cronos Price
0    1586476800000      0.053171
1    1586563200000      0.049563
2    1586649600000      0.050024
3    1586736000000      0.050062
4    1586822400000      0.049767
..             ...           ...
726  1649203200000      0.471989
727  1649289600000      0.440632
728  1649376000000      0.448653
729  1649462400000      0.436403
730  1649521006000      0.437563

[731 rows x 2 columns]

In [39]:
cronprice.to_csv("cron.csv")

In [49]:
volcron = cg.get_coin_market_chart_by_id("crypto-com-chain", "usd", 730)
volcron1=pd.DataFrame(volcron['total_volumes'], columns=['Time','Cronos Volume'])
volcron1

              Time  Cronos Volume
0    1586476800000   7.524231e+06
1    1586563200000   6.586185e+06
2    1586649600000   6.679442e+06
3    1586736000000   6.662411e+06
4    1586822400000   5.896746e+06
..             ...            ...
726  1649203200000   7.151299e+07
727  1649289600000   8.810043e+07
728  1649376000000   6.680808e+07
729  1649462400000   6.642291e+07
730  1649521006000   4.898937e+07

[731 rows x 2 columns]

In [50]:
volcron1.to_csv("cronVol.csv")

In [44]:
marketcapcron = cg.get_coin_market_chart_by_id("crypto-com-chain", "usd", 730)
cronMC=pd.DataFrame(marketcapcron['market_caps'], columns=['Time','Cronos Market Cap'])
cronMC

              Time  Cronos Market Cap
0    1586736000000       7.174690e+08
1    1586822400000       7.087251e+08
2    1586908800000       7.124800e+08
3    1586995200000       6.867414e+08
4    1587081600000       7.176443e+08
..             ...                ...
726  1649462400000       1.100808e+10
727  1649548800000       1.123003e+10
728  1649635200000       1.120411e+10
729  1649721600000       1.019331e+10
730  1649731904000       1.028212e+10

[731 rows x 2 columns]

In [45]:
cronMC.to_csv("cronMC.csv")

In [44]:
historic_priceaval = cg.get_coin_market_chart_by_id("avalanche-2", "usd", 730)
avalprice=pd.DataFrame(historic_priceaval['prices'], columns=['Time','Avalanche Price'])
avalprice

              Time  Avalanche Price
0    1600732800000         5.284244
1    1600819200000         5.284244
2    1600905600000         3.491229
3    1600992000000         4.573891
4    1601078400000         4.702974
..             ...              ...
561  1649203200000        91.092547
562  1649289600000        82.886209
563  1649376000000        87.955600
564  1649462400000        83.715830
565  1649521622000        82.894434

[566 rows x 2 columns]

In [45]:
avalprice.to_csv("aval.csv")

In [51]:
volavalanche = cg.get_coin_market_chart_by_id("avalanche-2", "usd", 730)
volaval=pd.DataFrame(volavalanche['total_volumes'], columns=['Time','Avalanche Volume'])
volaval

              Time  Avalanche Volume
0    1600732800000      2.458573e+08
1    1600819200000      2.458573e+08
2    1600905600000      9.734243e+07
3    1600992000000      6.966517e+07
4    1601078400000      4.195075e+07
..             ...               ...
561  1649203200000      1.033423e+09
562  1649289600000      1.603898e+09
563  1649376000000      1.357969e+09
564  1649462400000      1.355732e+09
565  1649521622000      8.114872e+08

[566 rows x 2 columns]

In [52]:
volaval.to_csv("avalVol.csv")

In [53]:
marketcapaval = cg.get_coin_market_chart_by_id("avalanche-2", "usd", 730)
avalMC=pd.DataFrame(marketcapaval['market_caps'], columns=['Time','Avalanche Market Cap'])
avalMC

              Time  Avalanche Market Cap
0    1600732800000          1.243579e+08
1    1600819200000          1.243579e+08
2    1600905600000          8.633525e+07
3    1600992000000          1.122094e+08
4    1601078400000          1.154319e+08
..             ...                   ...
561  1649203200000          2.447479e+10
562  1649289600000          2.236067e+10
563  1649376000000          2.364650e+10
564  1649462400000          2.228003e+10
565  1649521622000          2.217405e+10

[566 rows x 2 columns]

In [54]:
avalMC.to_csv("avalMC.csv")

In [55]:
historic_pricefantom = cg.get_coin_market_chart_by_id("fantom", "usd", 730)
fantomprice=pd.DataFrame(historic_pricefantom['prices'], columns=['Time','Fantom Price'])
fantomprice

              Time  Fantom Price
0    1586476800000      0.003793
1    1586563200000      0.003307
2    1586649600000      0.003309
3    1586736000000      0.003374
4    1586822400000      0.003414
..             ...           ...
726  1649203200000      1.454651
727  1649289600000      1.303942
728  1649376000000      1.350759
729  1649462400000      1.245745
730  1649522422000      1.263165

[731 rows x 2 columns]

In [56]:
fantomprice.to_csv("fantom.csv")

In [57]:
volfantom = cg.get_coin_market_chart_by_id("fantom", "usd", 730)
volfantom1=pd.DataFrame(volfantom['total_volumes'], columns=['Time','Fantom Volume'])
volfantom1

              Time  Fantom Volume
0    1586476800000   2.173222e+06
1    1586563200000   2.280835e+06
2    1586649600000   2.339508e+06
3    1586736000000   1.684559e+06
4    1586822400000   1.955905e+06
..             ...            ...
726  1649203200000   5.501345e+08
727  1649289600000   9.302908e+08
728  1649376000000   5.494603e+08
729  1649462400000   4.576184e+08
730  1649522422000   3.897682e+08

[731 rows x 2 columns]

In [58]:
volfantom1.to_csv("fantomVol.csv")

In [59]:
marketcapfantom = cg.get_coin_market_chart_by_id("fantom", "usd", 730)
fantomMC=pd.DataFrame(marketcapfantom['market_caps'], columns=['Time','Fantom Market Cap'])
fantomMC

              Time  Fantom Market Cap
0    1586476800000       7.963133e+06
1    1586563200000       7.010469e+06
2    1586649600000       7.003354e+06
3    1586736000000       7.166472e+06
4    1586822400000       7.273140e+06
..             ...                ...
726  1649203200000       3.714821e+09
727  1649289600000       3.325379e+09
728  1649376000000       3.434371e+09
729  1649462400000       3.154277e+09
730  1649522422000       3.211126e+09

[731 rows x 2 columns]

In [60]:
fantomMC.to_csv("fantomMC.csv")

In [61]:
historic_priceethereum = cg.get_coin_market_chart_by_id("ethereum", "usd", 730)
ethprice=pd.DataFrame(historic_priceethereum['prices'], columns=['Time','Ethereum Price'])
ethprice

              Time  Ethereum Price
0    1586476800000      170.095104
1    1586563200000      157.740158
2    1586649600000      158.327878
3    1586736000000      158.863826
4    1586822400000      156.701359
..             ...             ...
726  1649203200000     3422.969884
727  1649289600000     3171.371104
728  1649376000000     3232.834989
729  1649462400000     3192.025091
730  1649523113000     3226.579728

[731 rows x 2 columns]

In [62]:
ethprice.to_csv("eth.csv")

In [63]:
volethereum = cg.get_coin_market_chart_by_id("ethereum", "usd", 730)
voleth=pd.DataFrame(volethereum['total_volumes'], columns=['Time','Ethereum Volume'])
voleth

              Time  Ethereum Volume
0    1586476800000     1.197179e+10
1    1586563200000     1.413592e+10
2    1586649600000     1.112899e+10
3    1586736000000     1.300280e+10
4    1586822400000     1.328648e+10
..             ...              ...
726  1649203200000     1.511406e+10
727  1649289600000     2.610976e+10
728  1649376000000     1.614978e+10
729  1649462400000     1.752394e+10
730  1649523113000     1.250607e+10

[731 rows x 2 columns]

In [64]:
voleth.to_csv("ethVol.csv")

In [65]:
marketcapeth = cg.get_coin_market_chart_by_id("ethereum", "usd", 730)
ethMC=pd.DataFrame(marketcapeth['market_caps'], columns=['Time','Ethereum Market Cap'])
ethMC

              Time  Ethereum Market Cap
0    1586476800000         1.878745e+10
1    1586563200000         1.737512e+10
2    1586649600000         1.748957e+10
3    1586736000000         1.779041e+10
4    1586822400000         1.731664e+10
..             ...                  ...
726  1649203200000         4.129449e+11
727  1649289600000         3.828087e+11
728  1649376000000         3.888673e+11
729  1649462400000         3.826629e+11
730  1649523113000         3.880360e+11

[731 rows x 2 columns]

In [66]:
ethMC.to_csv("ethMC.csv")

In [67]:
historic_pricebnb = cg.get_coin_market_chart_by_id("binancecoin", "usd", 730)
bnbprice=pd.DataFrame(historic_pricebnb['prices'], columns=['Time','Binance Price'])
bnbprice

              Time  Binance Price
0    1586476800000      15.028759
1    1586563200000      13.718826
2    1586649600000      13.826759
3    1586736000000      14.265117
4    1586822400000      15.045573
..             ...            ...
726  1649203200000     446.692828
727  1649289600000     420.521418
728  1649376000000     437.092422
729  1649462400000     421.468652
730  1649523509000     423.415557

[731 rows x 2 columns]

In [68]:
bnbprice.to_csv("bnb.csv")

In [69]:
volbinance = cg.get_coin_market_chart_by_id("binancecoin", "usd", 730)
volbnb=pd.DataFrame(volbinance['total_volumes'], columns=['Time','Binance Volume'])
volbnb

              Time  Binance Volume
0    1586476800000    3.652217e+08
1    1586563200000    3.390273e+08
2    1586649600000    3.790711e+08
3    1586736000000    4.049799e+08
4    1586822400000    4.153753e+08
..             ...             ...
726  1649203200000    2.111671e+09
727  1649289600000    2.227804e+09
728  1649376000000    1.902419e+09
729  1649462400000    1.895965e+09
730  1649523509000    1.539115e+09

[731 rows x 2 columns]

In [70]:
volbnb.to_csv("bnbVol.csv")

In [71]:
marketcapbnb = cg.get_coin_market_chart_by_id("binancecoin", "usd", 730)
bnbMC=pd.DataFrame(marketcapbnb['market_caps'], columns=['Time','Binance Market Cap'])
bnbMC

              Time  Binance Market Cap
0    1586476800000        2.271676e+09
1    1586563200000        2.073911e+09
2    1586649600000        2.087482e+09
3    1586736000000        2.178117e+09
4    1586822400000        2.272858e+09
..             ...                 ...
726  1649203200000        7.525714e+10
727  1649289600000        7.091334e+10
728  1649376000000        7.349142e+10
729  1649462400000        7.059567e+10
730  1649523509000        7.128923e+10

[731 rows x 2 columns]

In [72]:
bnbMC.to_csv("bnbMC.csv")

In [73]:
historic_pricepoly = cg.get_coin_market_chart_by_id("polymath", "usd", 730)
polyprice=pd.DataFrame(historic_pricepoly['prices'], columns=['Time','PolyMath Price'])
polyprice

              Time  PolyMath Price
0    1586476800000        0.020419
1    1586563200000        0.018715
2    1586649600000        0.018466
3    1586736000000        0.018751
4    1586822400000        0.018010
..             ...             ...
726  1649203200000        0.485305
727  1649289600000        0.426554
728  1649376000000        0.443645
729  1649462400000        0.426783
730  1649523942000        0.427720

[731 rows x 2 columns]

In [74]:
polyprice.to_csv("poly.csv")

In [75]:
volpolymath = cg.get_coin_market_chart_by_id("polymath", "usd", 730)
volpoly=pd.DataFrame(volpolymath['total_volumes'], columns=['Time','Polymath Volume'])
volpoly

              Time  Polymath Volume
0    1586476800000     1.137351e+06
1    1586563200000     1.974125e+06
2    1586649600000     1.217371e+06
3    1586736000000     1.555734e+06
4    1586822400000     1.867479e+06
..             ...              ...
726  1649203200000     1.582625e+07
727  1649289600000     2.655821e+07
728  1649376000000     1.649691e+07
729  1649462400000     1.403973e+07
730  1649523942000     1.332954e+07

[731 rows x 2 columns]

In [76]:
volpoly.to_csv("polyVol.csv")

In [77]:
marketcappoly = cg.get_coin_market_chart_by_id("polymath", "usd", 730)
polyMC=pd.DataFrame(marketcappoly['market_caps'], columns=['Time','Polymath Market Cap'])
polyMC

              Time  Polymath Market Cap
0    1586476800000         1.267565e+07
1    1586563200000         1.160580e+07
2    1586649600000         1.145650e+07
3    1586736000000         1.175888e+07
4    1586822400000         1.127164e+07
..             ...                  ...
726  1649203200000         4.377498e+08
727  1649289600000         3.860890e+08
728  1649376000000         3.989134e+08
729  1649462400000         3.818549e+08
730  1649523942000         3.857708e+08

[731 rows x 2 columns]

In [78]:
polyMC.to_csv("polyMC.csv")

In [93]:
historic_pricerip = cg.get_coin_market_chart_by_id("ripple", "usd", 730)
ripprice=pd.DataFrame(historic_pricerip['prices'], columns=['Time','XRP Price'])
ripprice

              Time  XRP Price
0    1586649600000   0.188586
1    1586736000000   0.187934
2    1586822400000   0.188272
3    1586908800000   0.186109
4    1586995200000   0.181698
..             ...        ...
726  1649376000000   0.788300
727  1649462400000   0.754960
728  1649548800000   0.763627
729  1649635200000   0.756278
730  1649711528000   0.701034

[731 rows x 2 columns]

In [94]:
ripprice.to_csv("XRP.csv")

In [95]:
volripple= cg.get_coin_market_chart_by_id("ripple", "usd", 730)
volrip=pd.DataFrame(volripple['total_volumes'], columns=['Time','XRP Volume'])
volrip

              Time    XRP Volume
0    1586649600000  1.781002e+09
1    1586736000000  2.018968e+09
2    1586822400000  2.228365e+09
3    1586908800000  1.862120e+09
4    1586995200000  1.937689e+09
..             ...           ...
726  1649376000000  2.580151e+09
727  1649462400000  2.728014e+09
728  1649548800000  2.248539e+09
729  1649635200000  2.353543e+09
730  1649711528000  3.422791e+09

[731 rows x 2 columns]

In [96]:
volrip.to_csv("XRPVol.csv")

In [97]:
marketcaprip= cg.get_coin_market_chart_by_id("ripple", "usd", 730)
ripMC=pd.DataFrame(marketcaprip['market_caps'], columns=['Time','XRP Market Cap'])
ripMC

              Time  XRP Market Cap
0    1586649600000    8.293802e+09
1    1586736000000    8.265151e+09
2    1586822400000    8.299612e+09
3    1586908800000    8.202410e+09
4    1586995200000    8.011762e+09
..             ...             ...
726  1649376000000    3.794499e+10
727  1649462400000    3.622297e+10
728  1649548800000    3.674412e+10
729  1649635200000    3.640362e+10
730  1649711528000    3.375855e+10

[731 rows x 2 columns]

In [98]:
ripMC.to_csv("XRPMC.csv")

In [9]:
subcount= cg.get_coin_history_by_id(id='polymath',date=start_date, localization='false')
subscribers=subcount['developer_data']['subscribers']
subscribers

75

In [33]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcountsol= cg.get_coin_history_by_id(id='solana',date= sd, localization='false')
    subscriberssol=subcountsol['developer_data']['subscribers']
    sub.append(subscriberssol)
print (sub)

[None, 243, 244, 244, None, 248, 248, None, None, None, None, None, 244, None, 243, None, 245, None, 244, None, None, 243, None, None, 244, None, 244, 244, 245, 245, 245, None, None, 247, 247, 248, 248, 248, None, None, 248, 246, None, 247, 246, None, None, 245, 245, None, None]

In [20]:
results= pd.DataFrame(sub)
results.head()

       0
0  493.0
1  493.0
2  494.0
3  494.0
4  494.0

In [43]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcounttron= cg.get_coin_history_by_id(id='tron',date= sd, localization='false')
    subscriberstron=subcounttron['developer_data']['subscribers']
    sub.append(subscriberstron)
resultstron= pd.DataFrame(sub)
resultstron.head()

       0
0  340.0
1  340.0
2    NaN
3  340.0
4  339.0

In [37]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcountcron= cg.get_coin_history_by_id(id='crypto-com-chain',date= sd, localization='false')
    subscriberscron=subcountcron['developer_data']['subscribers']
    sub.append(subscriberscron)
print (sub)

[None, 40, 40, 40, None, None, None, 40, None, 40, 40, 39, None, None, 39, 39, 39, 39, None, 39, 39, None, 39, 39, 39, None, None, None, None, None, 39, 39, 40, 40, 40, 40, 40, None, 41, 41, None, None, None, 41, 42, None, 42, 42, 42, 42, 42]

In [38]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcountfant= cg.get_coin_history_by_id(id='fantom',date= sd, localization='false')
    subscribersfant=subcountfant['developer_data']['subscribers']
    sub.append(subscribersfant)
print (sub)

[27, 27, None, None, None, 27, None, 27, 27, 27, 27, 27, 27, 27, 27, None, 27, None, 27, 27, 27, 27, 27, 27, 27, None, 27, None, 27, 27, 27, 27, 27, None, 27, 27, None, None, 27, 27, None, 27, None, 27, 27, 27, 27, 28, None, 28, 28]

In [39]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcounteth= cg.get_coin_history_by_id(id='ethereum',date= sd, localization='false')
    subscriberseth=subcounteth['developer_data']['subscribers']
    sub.append(subscriberseth)
print (sub)

[2137, 2138, None, 2138, None, 2140, 2139, 2139, None, None, 2139, 2139, None, 2140, 2140, 2141, 2141, None, None, 2139, 2140, None, None, 2142, 2141, 2140, 2140, 2140, 2141, 2141, None, 2139, 2142, 2143, None, None, None, None, 2144, None, 2143, None, 2143, 2143, 2143, 2144, None, 2143, None, None, 2142]

In [40]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcountbnb= cg.get_coin_history_by_id(id='binancecoin',date= sd, localization='false')
    subscribersbnb=subcountbnb['developer_data']['subscribers']
    sub.append(subscribersbnb)
print (sub)

[510, 510, 510, None, 510, 510, None, 510, 511, 511, 511, 511, 511, 511, None, None, 511, 511, None, 511, None, 511, 511, 511, 511, None, 511, None, 511, None, 511, 511, 511, 511, 511, 511, None, None, None, None, 510, 510, 510, 510, None, 510, 510, 510, 510, 510, None]

In [41]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcountpoly= cg.get_coin_history_by_id(id='polymath',date= sd, localization='false')
    subscriberspoly=subcountpoly['developer_data']['subscribers']
    sub.append(subscriberspoly)
print (sub)

[75, 75, None, 75, 75, 75, 75, None, 75, 75, 75, None, 75, 75, None, 75, 75, 75, 75, None, 75, None, None, None, 75, 75, 75, 75, 75, 75, None, 75, None, 74, None, 74, 74, None, 74, None, 74, 74, None, 74, None, 74, 74, 74, 74, None, None]

In [15]:
from datetime import date, timedelta 
import datetime
start_date = date(2022, 2, 17)
end_date = date(2022, 4, 8)
sub = []
delta = timedelta(days=1)
while start_date <= end_date:
    start_date += delta
    sd = start_date.strftime("%d-%m-%Y")
    subcountxrp= cg.get_coin_history_by_id(id='ripple',date= sd, localization='false')
    subscribersxrp=subcountxrp['developer_data']['subscribers']
    sub.append(subscribersxrp)
print (sub)

[505, None, 505, 505, 505, 505, None, 505, None, 505, None, 505, None, 505, 505, 505, None, None, 505, None, 505, None, None, 505, 505, 505, 505, 505, 504, None, 504, 504, None, 504, None, None, None, 505, None, 506, None, 506, None, 506, None, 506, None, None, 505, 505, None]